server:
  port: 8007
spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: http://eureka7001.com:7001/eureka
