server:
  port: 8090

eureka:
  client:
    #是否将自己注册到注册中心, 默认true
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka  #单机版
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000
feign:
  hystrix:
    enabled: true
