server:
  port: 9527
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka #单机
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启注册中心路由功能,利用微服务名进行路由
      routes:
        - id: payment_routh
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址;
          predicates:
            - Path=/payment/lb/**



